name: Build Releases

on:
  push:
    tags:
      - 'v*' # Запускается, когда ты создаешь тег версии (например, v1.0.0)

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: .exe
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-action@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename Binary
        run: |
          cp target/${{ matrix.target }}/release/rust-task-manager${{ matrix.ext }} rust-task-manager-${{ matrix.target }}${{ matrix.ext }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: rust-task-manager-*
        env:
          GITHUB_TOKEN: ${{ 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 }}